In [2]:
import pandas as pd
import numpy as np
import seaborn as sns



data=pd.read_csv('D:/vibhav/Python/which employee left the company/human-resources-analytics (1)/HR_comma_sep.csv')
data.isnull()
data_renamed=data.rename(columns={'satisfaction_level':'Satisfaction','last_evaluation':'evaluation','number_project':'ProjectCount',
                     'average_montly_hours': 'averageMonthlyHours','time_spend_company': 'yearsAtCompany',
                        'Work_accident': 'workAccident', 'promotion_last_5years': 'promotion','sales' : 'department',
                                })

In [3]:
#Here we are considering left as label points so we are moving it to the front

columns_list=data_renamed.columns.tolist()
temp=columns_list[-4]
columns_list.remove('left')
columns_list.insert(0,temp)
data_reshuffled=data_renamed[columns_list]
data_reshuffled

,left,Satisfaction,evaluation,ProjectCount,averageMonthlyHours,yearsAtCompany,workAccident,promotion,department,salary
0,1,0.38,0.53,2,157,3,0,0,sales,low
1,1,0.80,0.86,5,262,6,0,0,sales,medium
2,1,0.11,0.88,7,272,4,0,0,sales,medium
3,1,0.72,0.87,5,223,5,0,0,sales,low
4,1,0.37,0.52,2,159,3,0,0,sales,low
5,1,0.41,0.50,2,153,3,0,0,sales,low
6,1,0.10,0.77,6,247,4,0,0,sales,low
7,1,0.92,0.85,5,259,5,0,0,sales,low
8,1,0.89,1.00,5,224,5,0,0,sales,low
9,1,0.42,0.53,2,142,3,0,0,sales,low
10,1,0.45,0.54,2,135,3,0,0,sales,low
11,1,0.11,0.81,6,305,4,0,0,sales,low
12,1,0.84,0.92,4,234,5,0,0,sales,low
13,1,0.41,0.55,2,148,3,0,0,sales,low
14,1,0.36,0.56,2,137,3,0,0,sales,low
15,1,0.38,0.54,2,143,3,0,0,sales,low
16,1,0.45,0.47,2,160,3,0,0,sales,low
17,1,0.78,0.99,4,255,6,0,0,sales,low
18,1,0.45,0.51,2,160,3,1,1,sales,low
19,1,0.76,0.89,5,262,5,0,0,sales,low
20,1,0.11,0.83,6,282,4,0,0,sales,low
21,1,0.38,0.55,2,147,3,0,0,sales,low
22,1,0.09,0.95,6,304,4,0,0,sales,low
23,1,0.46,0.57,2,139,3,0,0,sales,low
24,1,0.40,0.53,2,158,3,0,0,sales,low
25,1,0.89,0.92,5,242,5,0,0,sales,low
26,1,0.82,0.87,4,239,5,0,0,sales,low
27,1,0.40,0.49,2,135,3,0,0,sales,low
28,1,0.41,0.46,2,128,3,0,0,accounting,low
29,1,0.38,0.50,2,132,3,0,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
14969,1,0.43,0.46,2,157,3,0,0,sales,medium
14970,1,0.78,0.93,4,225,5,0,0,sales,medium
14971,1,0.39,0.45,2,140,3,0,0,sales,medium
14972,1,0.11,0.97,6,310,4,0,0,accounting,medium
14973,1,0.36,0.52,2,143,3,0,0,accounting,medium
14974,1,0.36,0.54,2,153,3,0,0,accounting,medium
14975,1,0.10,0.79,7,310,4,0,0,hr,medium
14976,1,0.40,0.47,2,136,3,0,0,hr,medium
14977,1,0.81,0.85,4,251,6,0,0,hr,medium
14978,1,0.40,0.47,2,144,3,0,0,hr,medium
14979,1,0.09,0.93,6,296,4,0,0,technical,medium
14980,1,0.76,0.89,5,238,5,0,0,technical,high
14981,1,0.73,0.93,5,162,4,0,0,technical,low
14982,1,0.38,0.49,2,137,3,0,0,technical,medium
14983,1,0.72,0.84,5,257,5,0,0,technical,medium
14984,1,0.40,0.56,2,148,3,0,0,technical,medium
14985,1,0.91,0.99,5,254,5,0,0,technical,medium
14986,1,0.85,0.85,4,247,6,0,0,technical,low
14987,1,0.90,0.70,5,206,4,0,0,technical,low
14988,1,0.46,0.55,2,145,3,0,0,technical,low
14989,1,0.43,0.57,2,159,3,1,0,technical,low
14990,1,0.89,0.88,5,228,5,1,0,support,low
14991,1,0.09,0.81,6,257,4,0,0,support,low
14992,1,0.40,0.48,2,155,3,0,0,support,low
14993,1,0.76,0.83,6,293,6,0,0,support,low
14994,1,0.40,0.57,2,151,3,0,0,support,low
14995,1,0.37,0.48,2,160,3,0,0,support,low
14996,1,0.37,0.53,2,143,3,0,0,support,low
14997,1,0.11,0.96,6,280,4,0,0,support,low
14998,1,0.37,0.52,2,158,3,0,0,support,low

# Statistical Overview

In [16]:
turnover_rate=data_reshuffled.left.value_counts()/14999
turnover_rate
#Here it shows that 76% of employees stayed and 24% employees left

0    0.761917
1    0.238083
Name: left, dtype: float64

# Moderate Positively Correlated Features:

projectCount vs evaluation: 0.349333
projectCount vs averageMonthlyHours: 0.417211
averageMonthlyHours vs evaluation: 0.339742
Moderate Negatively Correlated Feature:

satisfaction vs turnover: -0.388375
Stop and Think:

What features affect our target variable the most (turnover)?
What features have strong correlations with each other?
Can we do a more in depth examination of these features?
Summary:

From the heatmap, there is a positive(+) correlation between projectCount, averageMonthlyHours, and evaluation. Which could mean that the employees who spent more hours and did more projects were evaluated highly.

For the negative(-) relationships, turnover and satisfaction are highly correlated. I'm assuming that people tend to leave a company more when they are less satisfied.

# 4. Modeling the Data
The best model performance out of the four (Decision Tree Model, AdaBoost Model, Logistic Regression Model, Random Forest Model) was Random Forest!

Note: Base Rate

A Base Rate Model is a model that always selects the target variable's majority class. It's just used for reference to compare how better another model is against it. In this dataset, the majority class that will be predicted will be 0's, which are employees who did not leave the company.
If you recall back to Part 3: Exploring the Data, 24% of the dataset contained 1's (employee who left the company) and the remaining 76% contained 0's (employee who did not leave the company). The Base Rate Model would simply predict every 0's and ignore all the 1's.
Example: The base rate accuracy for this data set, when classifying everything as 0's, would be 76% because 76% of the dataset are labeled as 0's (employees not leaving the company).

In [7]:
# create dummy variable for the 'department' and 'salary' features,since they are categorical

# salary=pd.get_dummies(data_renamed['salary'],drop_first=True,prefix='sal')
# department=pd.get_dummies(data_renamed['department'],drop_first=True,prefix='dep')
# data_reshuffled.drop(['department','salary'],inplace=True,axis=1)
# df=pd.concat([data_reshuffled,salary,department],axis=1)
# df
data_reshuffled['salary']=pd.get_dummies(data_reshuffled['salary'])
data_reshuffled['department']=pd.get_dummies(data_reshuffled['department'])
data_reshuffled

,left,Satisfaction,evaluation,ProjectCount,averageMonthlyHours,yearsAtCompany,workAccident,promotion,department,salary
0,1,0.38,0.53,2,157,3,0,0,1,1
1,1,0.80,0.86,5,262,6,0,0,1,1
2,1,0.11,0.88,7,272,4,0,0,1,1
3,1,0.72,0.87,5,223,5,0,0,1,1
4,1,0.37,0.52,2,159,3,0,0,1,1
5,1,0.41,0.50,2,153,3,0,0,1,1
6,1,0.10,0.77,6,247,4,0,0,1,1
7,1,0.92,0.85,5,259,5,0,0,1,1
8,1,0.89,1.00,5,224,5,0,0,1,1
9,1,0.42,0.53,2,142,3,0,0,1,1
10,1,0.45,0.54,2,135,3,0,0,1,1
11,1,0.11,0.81,6,305,4,0,0,1,1
12,1,0.84,0.92,4,234,5,0,0,1,1
13,1,0.41,0.55,2,148,3,0,0,1,1
14,1,0.36,0.56,2,137,3,0,0,1,1
15,1,0.38,0.54,2,143,3,0,0,1,1
16,1,0.45,0.47,2,160,3,0,0,1,1
17,1,0.78,0.99,4,255,6,0,0,1,1
18,1,0.45,0.51,2,160,3,1,1,1,1
19,1,0.76,0.89,5,262,5,0,0,1,1
20,1,0.11,0.83,6,282,4,0,0,1,1
21,1,0.38,0.55,2,147,3,0,0,1,1
22,1,0.09,0.95,6,304,4,0,0,1,1
23,1,0.46,0.57,2,139,3,0,0,1,1
24,1,0.40,0.53,2,158,3,0,0,1,1
25,1,0.89,0.92,5,242,5,0,0,1,1
26,1,0.82,0.87,4,239,5,0,0,1,1
27,1,0.40,0.49,2,135,3,0,0,1,1
28,1,0.41,0.46,2,128,3,0,0,1,1
29,1,0.38,0.50,2,132,3,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
14969,1,0.43,0.46,2,157,3,0,0,1,1
14970,1,0.78,0.93,4,225,5,0,0,1,1
14971,1,0.39,0.45,2,140,3,0,0,1,1
14972,1,0.11,0.97,6,310,4,0,0,1,1
14973,1,0.36,0.52,2,143,3,0,0,1,1
14974,1,0.36,0.54,2,153,3,0,0,1,1
14975,1,0.10,0.79,7,310,4,0,0,1,1
14976,1,0.40,0.47,2,136,3,0,0,1,1
14977,1,0.81,0.85,4,251,6,0,0,1,1
14978,1,0.40,0.47,2,144,3,0,0,1,1
14979,1,0.09,0.93,6,296,4,0,0,1,1
14980,1,0.76,0.89,5,238,5,0,0,1,0
14981,1,0.73,0.93,5,162,4,0,0,1,1
14982,1,0.38,0.49,2,137,3,0,0,1,1
14983,1,0.72,0.84,5,257,5,0,0,1,1
14984,1,0.40,0.56,2,148,3,0,0,1,1
14985,1,0.91,0.99,5,254,5,0,0,1,1
14986,1,0.85,0.85,4,247,6,0,0,1,1
14987,1,0.90,0.70,5,206,4,0,0,1,1
14988,1,0.46,0.55,2,145,3,0,0,1,1
14989,1,0.43,0.57,2,159,3,1,0,1,1
14990,1,0.89,0.88,5,228,5,1,0,1,1
14991,1,0.09,0.81,6,257,4,0,0,1,1
14992,1,0.40,0.48,2,155,3,0,0,1,1
14993,1,0.76,0.83,6,293,6,0,0,1,1
14994,1,0.40,0.57,2,151,3,0,0,1,1
14995,1,0.37,0.48,2,160,3,0,0,1,1
14996,1,0.37,0.53,2,143,3,0,0,1,1
14997,1,0.11,0.96,6,280,4,0,0,1,1
14998,1,0.37,0.52,2,158,3,0,0,1,1

In [8]:
from sklearn.model_selection import train_test_split
labels=data_reshuffled['left']
data=data_reshuffled.iloc[:,1:]
X_train,X_test,y_train,y_test= train_test_split(data,labels)

In [12]:
#using 5 fold cross validation
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
#linreg=LinearRegression().fit(X_train,y_train)
linRidge=Ridge(alpha=5.0).fit(X_train, y_train)
print('Intercept',linRidge.intercept_)
print('Coefficeint',linRidge.coef_)
print('Training Score:',linRidge.score(X_train,y_train))
print('Test Score:',linRidge.score(X_test,y_test))

Intercept 0.306024049811
Coefficeint [-0.64743557  0.08391105 -0.03502648  0.00066458  0.03390769 -0.15769168
 -0.13449336  0.02465066  0.16579888]
Training Score: 0.202803510519
Test Score: 0.210258897821

In [23]:
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor().fit(X_train,y_train)
print('Training Score',clf.score(X_train,y_train))
print('Test Score',clf.score(X_test,y_test))
# example_record=[0.38,0.54,5,345,5,0,0,1,1]
# print('predict wether employee will leave or not',clf.predict(example_record))

Training Score 1.0
Test Score 0.894576384485

In [14]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_train, y_train)
print('Training score',clf.score(X_train,y_train))
print('Testing score',clf.score(X_test,y_test))

Training score 0.76753489199
Testing score 0.765066666667